services:
  mysql-estoque:
    image: mysql:8.0
    container_name: mysql-estoque
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_estoque
    ports:
      - "3308:3306"
    volumes:
      - ./data/mysql-estoque:/var/lib/mysql